### PR TITLE
Jbtm 2889 Include a vertx with STM quickstart

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.jboss.org/browse/JBTM-2889 Include a vertx with STM quickstart

I have reopened this JIRA since I want to replace the [quickstart](https://github.com/jbosstm/conferences/tree/master/mucon2017 ) with a link to a better one in our conferences repositiory.

NO_TEST

### CODE REVIEW

**Comment by nmcl** [comment]
Is this missing a title, other than Jbtm 2889?

**Comment by mmusgrov** [comment]
@nmcl Sometimes the PR comment skips the commit description. I have manually updated the title and comment.

**Comment by zhfeng** [comment]
It looks like a conflict with pom.xml and I think you need to rebase it

**Comment by mmusgrov** [comment]
@zhfeng Yes but is it okay otherwise?

**Pull request merged**
