### PR TITLE
JBTM-3569: Test failures on jta-and-hibernate-standalone quickstart

### PR DESCRIPTION
**Pull request by mayankkunwar**
[JBTM-3569](https://issues.redhat.com/browse/JBTM-3569)

### CODE REVIEW

**Comment by mmusgrov** [comment]
@mayankkunwar do you have any thoughts about why the transactional driver quickstart failed.
Would a similar fix to this PR work:

`Can't create table by 'CREATE TABLE TXN_DRIVER_TEST(id int primary key, value varchar(42))'`

ie replace `value` with `val`

**Comment by mayankkunwar** [comment]
@mmusgrov I already tried that. There are some test failures after replacing `value` with `val`

```
Tests in error: 
  transactionDriverIndirectRecoverableRecovery2(io.narayana.TransactionalDriverTest): Error on closing multiple closable statemens: [com.arjuna.ats.internal.jdbc.ConnectionImple@5656be13, com.arjuna.ats.internal.jdbc.ConnectionImple@235834f2]
  transactionDriverIndirectRecoverableRecovery(io.narayana.TransactionalDriverTest): Error on closing multiple closable statemens: [com.arjuna.ats.internal.jdbc.ConnectionImple@7eac9008, com.arjuna.ats.internal.jdbc.ConnectionImple@1fa121e2]
  transactionDriverIndirectRollback(io.narayana.TransactionalDriverTest): Can't create table by 'CREATE TABLE TXN_DRIVER_TEST(id int primary key, val varchar(42))'
  transactionDriverDirectRecoverableRollback(io.narayana.TransactionalDriverTest): Can't create table by 'CREATE TABLE TXN_DRIVER_TEST(id int primary key, val varchar(42))'
  transactionDriverProvidedRecovery(io.narayana.TransactionalDriverTest): Can't create table by 'CREATE TABLE TXN_DRIVER_TEST(id int primary key, val varchar(42))'

Tests run: 14, Failures: 0, Errors: 5, Skipped: 0

```

**Comment by mmusgrov** [comment]
> @mmusgrov I already tried that. There are some test failures after replacing `value` with `val`
> 
> ```
> Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TXN_DRIVER_TEST" already exists; SQL statement:
> 
> Tests run: 14, Failures: 0, Errors: 5, Skipped: 0
> ```

@mayankkunwar Why can't you either delete it or use "CREATE DATABASE IF NOT EXISTS etc"?

**Comment by mayankkunwar** [comment]
Seems like this issue is fixed as part of https://github.com/jbosstm/quickstart/pull/376. Withdrawing this PR and will create separate PR for transactionaldriver-standalone quickstart

**Comment by mayankkunwar** [comment]
@tomjenkinson `IllegalStateException` was for `transactionaldriver-standalone` quickstart failure. So for that I will raise separate JIRA and PR.

**Pull request closed without merging**
