### PR TITLE
Jbtm 3462 ci tests

### PR DESCRIPTION
**Pull request by moulalis**
DO NOT REVIEW AND MERGE, THIS IS JUST TO TEST THE CI

### CODE REVIEW

**Comment by mmusgrov** [comment]
I've marked it on hold because Moulalis just wants to see if it works on CI.

**Comment by moulalis** [comment]
@mmusgrov rebase done, could you please start the test job now?

**Comment by moulalis** [comment]
Thank you @mmusgrov, My changes worked successfully. I will integrat the same with https://github.com/jbosstm/quickstart/pull/434.

**Comment by mmusgrov** [comment]
ok in that case I will close this one

**Pull request closed without merging**
