### PR TITLE
[Jbtm 3733]: Implement checkstyle to the Narayana SPI and quickstart modules

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBTM-3733

Note: Checkstyle not applied to all the Arjuna code.
(Checkstyle is set to false)

Keeping it on hold as we are still discussing on checkstyle to be applied or no.
(Hold label removed)

### CODE REVIEW

**Review by mmusgrov — CHANGES_REQUESTED** [review]
You just need to add the plugin, making sure it is skipped by default. See my [comment on the other PR](https://github.com/jbosstm/jboss-transaction-spi/pull/40#issuecomment-1692882720) for the justification.

**Review by mmusgrov — APPROVED** [review]
Thanks Moulalis for this change.

I'm approving, but note that there is still a debate to be had about the purpose of a quickstart and one can argue that having a consistent collection lowers the barriers to adoption so I would not necessarily be averse to enabling checkstyle by default for the quickstart repo. But I'd be less enthusiastic about applying reformatting tools without due care and attention its output (/cc @marcosgopen and @jmfinelli ).

**Review by marcosgopen — APPROVED** [review]
Thanks Moulali for your PR!

**Comment by marcosgopen** [comment]
> Thanks Moulalis for this change.
> 
> I'm approving, but note that there is still a debate to be had about the purpose of a quickstart and one can argue that having a consistent collection lowers the barriers to adoption so I would not necessarily be averse to enabling checkstyle by default for the quickstart repo. But I'd be less enthusiastic about applying reformatting tools without due care and attention its output (/cc @marcosgopen and @jmfinelli ).

Thanks 

> Thanks Moulalis for this change.
> 
> I'm approving, but note that there is still a debate to be had about the purpose of a quickstart and one can argue that having a consistent collection lowers the barriers to adoption so I would not necessarily be averse to enabling checkstyle by default for the quickstart repo. But I'd be less enthusiastic about applying reformatting tools without due care and attention its output (/cc @marcosgopen and @jmfinelli ).

I would like to encourage developers to check new quickstarts respect checkstyle rules when possible, but I think quickstarts should be easy to use so I would understand if they prefer not to enable the checktyle plugin.  I agree with Mike that reformatting tools should be used with care (only for essential formatting). 

Quoting our CONTRIBUTING guide:
"a file (in a module with checkstyle disabled) may only be re-formatted if it also contains a functional change and is made in a separate commit"

**Comment by moulalis** [comment]
Thank you @marcosgopen and @mmusgrov , Narayan PR experiences have ultimately provided us with valuable insights to take away.

**Pull request merged**
