### PR TITLE
[JBTM-2444] Update JMS config to work with ActiveMQ

### PR DESCRIPTION
**Pull request by gytis**

### CODE REVIEW

**Comment by gytis** [comment]
JTA 1.2 test passed now. But REST-AT bridge test failed, which also uses JMS.

**Comment by zhfeng** [comment]
The REST-AT tests use the standalone-rts.xml which I think it still uses "messaging.xml" in the
https://github.com/wildfly/wildfly/blob/master/feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml
So it looks like need to change to use "messaging-activemq.xml' ?

**Comment by gytis** [comment]
Yeah I've noticed that. I've commented on WFLY-4584, to check with Jeff.

**Comment by gytis** [comment]
Rebuilding WildFly locally to see if adding messaging-activemq fixes the problem.

**Comment by zhfeng** [comment]
It looks like the hornetq messaging subsystem has been removed to the legacy.
https://github.com/wildfly/wildfly/commit/c9c2590c0424ed4903cb174b448f8b7c335fe1eb

**Comment by gytis** [comment]
Seems that it doesn't automatically provide JMS API by scanning the deployment. Therefore, JMSException class is not found.
I've updated https://github.com/wildfly/wildfly/blob/master/feature-pack/src/main/resources/configuration/examples/subsystems-rts.xml to use messaging-activemq.xml instead of messaging.xml and it works. Seems that they have just forgotten to update them.

**Comment by gytis** [comment]
Seems that they're planning to implement backwards compatibility https://issues.jboss.org/browse/WFLY-4586

**Comment by gytis** [comment]
Modified quickstarts have passed

**Pull request merged**
