### PR TITLE
JBTM-3764 Change license (Apache-2.0) and remove copyright headers

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3764

This PR follows up on a similar change to the main repo (https://github.com/jbosstm/narayana/pull/2140) and changes the license and removes per file copyright statements

### CODE REVIEW

**Comment by marcosgopen** [comment]
I can see you removed the license and copyright statements in all the files. In the main repo you replaced it with the new one (i.e. https://github.com/jbosstm/narayana/pull/2140/files#diff-ff09fc83e8f9fb9c9a88403627cfa5df93f1ec449e29925794baa2ed753fb766R2-R3). Is it intended not to have the new license and copytight statement in java and xml files in quickstart?

**Review by marcosgopen — APPROVED** [review]
Thanks @mmusgrov for your PR. As you wrote in the CONTRIBUTING.md we prefer removing license and copyright from quickstart files to make "it easier for developers to use the quickstarts to jumpstart their own development". However the license for this repo is well described in the LICENSE file. We know there are automatic tools  that check license in the files, but we don't expect these quickstarts to be imported in other projects. Instead we expect quickstarts to be helpful for users to learn about Narayana and reuse them easily. Do you agree with me @mmusgrov ?

**Comment by mmusgrov** [comment]
The PR failures are expected (they're new and we are investigating).

**Comment by mmusgrov** [comment]
> Thanks @mmusgrov for your PR. As you wrote in the CONTRIBUTING.md we prefer removing license and copyright from quickstart files to make "it easier for developers to use the quickstarts to jumpstart their own development". However the license for this repo is well described in the LICENSE file. We know there are automatic tools that check license in the files, but we don't expect these quickstarts to be imported in other projects. Instead we expect quickstarts to be helpful for users to learn about Narayana and reuse them easily. Do you agree with me @mmusgrov ?

That is a good explanation of why we don't want them in this repo so I agree with you.

**Pull request merged**
