### PR TITLE
Updated lra quickstart

### PR DESCRIPTION
**Pull request by mkralik3**
Signed-off-by: mkralik3 <mkralik@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:
- [ ] Pull Request title is properly formatted: JBTM-XYZ Subject
- [ ] Pull Request contains link to the JIRA issue(s)
- [ ] For new quickstarts, you should add it to the list in the top level README and you can mark it with some labels (if you wish)

### CODE REVIEW

**Comment by ochaloup** [comment]
TESTIT

**Comment by ochaloup** [comment]
@tomjenkinson would you like the jira issue to be created or as this is just a smaller fix with no further functionality update it's ok to be as it is?

**Comment by ochaloup** [comment]
I think the JBTM-3150 is fine.
@mkralik3 could you please update the commit message of the PR with declaring the issue plus adding something about the commit? Like...
```
[JBTM-3150] LRA quickstart  update for use of thorntail
```

**Comment by mkralik3** [comment]
@ochaloup Yes

**Comment by ochaloup** [comment]
@mkralik3 perfect, thanks for the contribution

**Pull request merged**
