### PR TITLE
[JBTM-3463] split up each service (hotel, flight and trip) so that th…

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/JBTM-3463

### CODE REVIEW

**Comment by marcosgopen** [comment]
Thanks @moulalis for your PR! I would suggest to join this PR with the already existing one: https://github.com/jbosstm/quickstart/pull/434
Or to merge the existing one (https://github.com/jbosstm/quickstart/pull/434) that migrates the sra-participant from Narayana main repo (git history too) and then merge this PR. WDYT?

**Comment by marcosgopen** [comment]
> > Thanks @moulalis for your PR! I would suggest to join this PR with the already existing one: #434 Or to merge the existing one (#434) that migrates the sra-participant from Narayana main repo (git history too) and then merge this PR. WDYT?
> 
> Hi @marcosgopen I understand, but this can be merged before [434](https://github.com/jbosstm/quickstart/pull/434). This is different and having no dependency on it. For [434](https://github.com/jbosstm/quickstart/pull/434) I have to work on history part which may take time.

I think you first need to import the code with history and then you can start splitting each service, otherwise you will have 2 different histories that are not 'merge-able'. WDYT @mmusgrov ?

**Comment by moulalis** [comment]
> > > Thanks @moulalis for your PR! I would suggest to join this PR with the already existing one: #434 Or to merge the existing one (#434) that migrates the sra-participant from Narayana main repo (git history too) and then merge this PR. WDYT?
> > 
> > 
> > Hi @marcosgopen I understand, but this can be merged before [434](https://github.com/jbosstm/quickstart/pull/434). This is different and having no dependency on it. For [434](https://github.com/jbosstm/quickstart/pull/434) I have to work on history part which may take time.
> 
> I think you first need to import the code with history and then you can start splitting each service, otherwise you will have 2 different histories that are not 'merge-able'. WDYT @mmusgrov ?

I am assuming this is separate issue/task. WDYT @mmusgrov ?

**Comment by mmusgrov** [comment]
> > > > Thanks @moulalis for your PR! I would suggest to join this PR with the already existing one: #434 Or to merge the existing one (#434) that migrates the sra-participant from Narayana main repo (git history too) and then merge this PR. WDYT?
> > > 
> > > 
> > > Hi @marcosgopen I understand, but this can be merged before [434](https://github.com/jbosstm/quickstart/pull/434). This is different and having no dependency on it. For [434](https://github.com/jbosstm/quickstart/pull/434) I have to work on history part which may take time.
> > 
> > 
> > I think you first need to import the code with history and then you can start splitting each service, otherwise you will have 2 different histories that are not 'merge-able'. WDYT @mmusgrov ?
> 
> I am assuming this is separate issue/task. WDYT @mmusgrov ?

The changes need to be staged:

- stage one is move the code with full history;
- stage two is split up the service into three services.

**Review by mmusgrov — CHANGES_REQUESTED** [review]
I've just finished reviewing the README in pr/434 and it contains the same set of diffs. I am requesting changes since it is not clear which one I should be reviewing?

**Comment by mmusgrov** [comment]
It might be simpler to move the files over to the new repo and then do the split. Having two PRs running in parallel for this work makes it awkward for reviewers, it also means that we'll have moved the demo code out our the main repo prior to doing a release which I'd like to do very soon (to pick up Marcos fix for a REST-AT issue and hopefully we'll have the re-licensing done this week).

**Comment by moulalis** [comment]
@mmusgrov @marcosgopen This PR is merged with https://github.com/jbosstm/quickstart/pull/434, so  can we safely close it? Thanks.

**Comment by mmusgrov** [comment]
@moulalis You should already have permission to close it, let us know if you don't.

**Comment by moulalis** [comment]
> @moulalis You should already have permission to close it, let us know if you don't.

I have the permission I was asking your permission can it be closed. Closing it now. Thanks.

**Pull request closed without merging**
