### PR TITLE
JBTM-3487  Fix typo inside spring/camel-with-narayana-spring-boot/Rea…

### PR DESCRIPTION
**Pull request by gautric**
…dme.md

the recovery mode command line is wrong

https://issues.redhat.com/browse/JBTM-3487

Please make sure your PR meets the following requirements:
- [X] Pull Request title is properly formatted: JBTM-XYZ Subject
- [X] Pull Request contains link to the JIRA issue(s)
- [ ] For new quickstarts, you should add it to the list in the top level README and you can mark it with some labels (if you wish)

### CODE REVIEW

**Comment by zhfeng** [comment]
Thanks @gautric  and TESTIT please !

**Comment by zhfeng** [comment]
TESTIT

**Review by zhfeng — APPROVED** [review]
LGTM

**Comment by ochaloup** [comment]
The failure of the PR is trouble of a different quickstart `LRA Quickstart lra-test locally`. As Amos approved I think we can merge.

**Review by ochaloup — APPROVED** [review]
Seems fine to me.

**Comment by ochaloup** [comment]
@gautric thanks a lot for the fix!

**Pull request merged**
