### PR TITLE
quarkus update to 3.4.2

### PR DESCRIPTION
**Pull request by marcosgopen**
Update quarkus to 3.4.2 version

This PR will be on hold until https://github.com/jbosstm/narayana/pull/2177 get merged.

Note: I added an extra commit in order to fix the failure shown in [CI build](https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-narayana-quickstart/17/)

### CODE REVIEW

**Comment by marcosgopen** [comment]
This PR should solve error shown in CI build https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/narayana-quickstarts/

**Comment by mmusgrov** [comment]
@marcosgopen The test failure is because of `java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory`.
We aren't logging the target of the InvocationTargetException on line https://github.com/jbosstm/narayana/blob/7.0.0.Final/common/classes/com/arjuna/common/internal/util/ClassloadingUtility.java#L128

**Comment by mmusgrov** [comment]
Note that the problem will be due to the recent upgrade of org.apache.activemq from 2.24.0 to 2.30.0.

**Review by mmusgrov — APPROVED** [review]
Very good.

**Pull request merged**
